license="${mod_license}"
issueTrackerURL="https://github.com/Ametrin-Studios/BlockVariantsBOP/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://curseforge.com/minecraft/mc-mods/block-variants-biomes-o-plenty" #optional
#logoFile="examplemod.png" #optional
#credits="" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    # The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
    type="required" #mandatory
    # reason="..."
    # The version range of the dependency
    versionRange="${neo_version_range}" #mandatory
    # An ordering relationship for the dependency.
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="block_variants"
    type="required"
    versionRange="${bv_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="biomesoplenty"
    type="required"
    versionRange="${bop_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ametrin"
    type="required"
    versionRange="${ametrin_version_range}"
    ordering="NONE"
    side="BOTH"
