modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Ametrin-Studios/BlockVariantsBOP/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Ametrin-Studios/BlockVariantsBOP/refs/heads/main/update.json" #optional
displayURL="https://curseforge.com/minecraft/mc-mods/block-variants-biomes-o-plenty" #optional
logoFile="logo.png" #optional
#credits="" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="block_variants"
    type="required"
    versionRange="${bv_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="biomesoplenty"
    type="required"
    versionRange="${bop_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ametrin"
    type="required"
    versionRange="${ametrin_version_range}"
    ordering="NONE"
    side="BOTH"
